quarkus.http.limits.max-body-size=8192

loader.license-provider.mode=unconfigured

%dev.loader.license-provider.mode=mock
%dev.loader.mock.enabled=true
%dev.loader.mock-license=dev-license
%dev.loader.signing.key-id=dev-2026
%dev.loader.signing.private-key-pkcs8-base64=MC4CAQAwBQYDK2VwBCIEIJ1hsZ3v/VpguoRK9JLsLMREScVpezJpGXA7rAMcrn9g
%dev.loader.signing.public-key-x509-base64=MCowBQYDK2VwAyEA11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo=
%dev.loader.artifact.root=artifacts
%dev.loader.artifact.product-id=demo-plugin
%dev.loader.artifact.channel=stable
%dev.loader.artifact.id=demo-release
%dev.loader.artifact.filename=demo-plugin.jar
